services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db   # usa o H2 embutido p/ aula
    volumes:
      - ./metabase-data:/metabase-data
    depends_on:
      - webserver
