name: 'pos-ia-mod-2-main'
version: '1.0.0'
config-version: 2

profile: 'pos-ia-mod-2-main'

model-paths: ['models']
seed-paths: ['seeds']
analysis-paths: ['analysis']
test-paths: ['tests']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  pos-ia-mod-2-main:
    +materialized: view
