name: 'laboratorio_dbt'
version: '1.0.0'
config-version: 2

profile: 'laboratorio_dbt'

model-paths: ['models']
seed-paths: ['seeds']
analysis-paths: ['analysis']
test-paths: ['tests']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  laboratorio_dbt:
    +materialized: view
